#!/bin/bash
# Written by lithid (mrlithid@gmail.com)
export CMC_HOME=${CMC_HOME:-$(dirname $0)}
if [ -n "${CMC_HOME##*/*}" ];
then
	#dirname didn't give us a full path, try PWD
	export CMC_HOME=$(pwd -P)
fi

. $CMC_HOME/tools/f/compile_functions
chk_tmp
get_colors_set
chk_cmc_config
chk_adb_running
undo_repo_changes

if [ ! -f $TMP_REPO ]; then
	chk_repo_path
fi

clear
echo -e "<<< "$CLR"Welcome to the Cyanogenmod Compiler"$toff" >>>
"$CLR"Main"$toff"
Repos Found: "$CLR"$FOUND_NUM"$toff"

	"$CLR"1"$toff") Setup cyanogenmod repo (GB/ICS)
	"$CLR"2"$toff") Update repo (GB/ICS)
	-----
	"$CLR"3"$toff") Choose your manufacturer
	"$CLR"4"$toff") Choose your model
	"$CLR"5"$toff") Extract Files: "$CLR"$DEVICE_MOD"$toff"
	-----
	"$CLR"6"$toff") Remove languages (GB/ICS)
	"$CLR"7"$toff") Remove live wallpapers (GB/ICS)
	"$CLR"8"$toff") Remove cm wallpapers (GB)
	-----
	"$CLR"9"$toff") Compile cyanogenmod (GB/ICS)
	-----
	"$CLR"10"$toff") Undo current changes: "$CLR"$CHANGE_COUNT"$toff"
	-----
	"$CLR"P"$toff") CMC Plugins
	-----
	"$CLR"97"$toff") Toggle git/https syncing
	"$CLR"98"$toff") Change theme
	"$CLR"99"$toff") Information about CMC
	"$CLR"X"$toff") exit

Device Info: "$CLR"$DEVICE_MAN"$toff"/"$CLR"$DEVICE_MOD"$toff" ADB: $ADB_MSG
Please choose an option to continue"
echo -n "> "

read option
case $option in
	1)
		. $CMC_HOME/menu_items/setup_cm_repo.menu;;
	2)
		. $CMC_HOME/menu_items/update_cm_repo.menu;;
	3)
		. $CMC_HOME/menu_items/ch_manufacturer.menu;;
	4)
		. $CMC_HOME/menu_items/ch_model.menu;;
	5)
		. $CMC_HOME/menu_items/extract_files.menu;;
	6)
		. $CMC_HOME/menu_items/ch_rem_languages.menu;;
	7)
		. $CMC_HOME/menu_items/ch_rem_live_wallpaper.menu;;
	8)
		. $CMC_HOME/menu_items/ch_rem_cm_wallpaper.menu;;
	9)
		. $CMC_HOME/menu_items/compile_cm_repo.menu;;
	10)
		. $CMC_HOME/menu_items/undo_repo_changes.menu;;
	97)
		. $CMC_HOME/menu_items/toggle_git_https.menu;;
	98)
		. $CMC_HOME/menu_items/ch_theme.menu;;
	99)
		;;
	p|P)
		. $CMC_HOME/menu_items/run_plugins.menu;;
	x|X)
		echo "Goodbye!"
		chk_tmp
		exit 0;;
	*)
		$MAIN;;
esac
