#!/system/bin/sh
# Created by tommytomatoe

rm /data/dalvik-cache/*;
rm /cache/dalvik-cache/*;
FRAME=$(ls /system/framework |grep ".jar" |grep -v core |grep -v bouncycastle |grep -v ext |grep -v framework |grep -v android_policy |grep -v services |grep -v core-junit)
odex_core_aosp_gb()
{
	dexopt-wrapper /system/framework/core.jar /system/framework/core.odex;
	dexopt-wrapper /system/framework/bouncycastle.jar /system/framework/bouncycastle.odex
	dexopt-wrapper /system/framework/ext.jar /system/framework/ext.odex;
	dexopt-wrapper /system/framework/framework.jar /system/framework/framework.odex
	dexopt-wrapper /system/framework/android.policy.jar /system/framework/android.policy.odex;
	dexopt-wrapper /system/framework/services.jar /system/framework/services.odex;
	dexopt-wrapper /system/framework/core-junit.jar /system/framework/core-junit.odex
}

odex_framework()
{
	for i in $FRAME
		do
			odex=`echo $i | sed -e 's/.jar/.odex/g'`
			dexopt-wrapper $i $odex
		done
}

odex_system()
{
	for i in /system/app/*.apk
	do
	odex=`echo $i | sed -e 's/.apk/.odex/g'`
	dexopt-wrapper $i $odex
	done
}

odex_data()
{
	for i in /data/app/*.apk
		do
			odex=`echo $i | sed -e 's/.apk/.odex/g'`
			dexopt-wrapper $i $odex
		done

	for i in /data/app-private/*.apk
		do
			odex=`echo $i | sed -e 's/.apk/.odex/g'`
			dexopt-wrapper $i $odex
		done
}
odex_core_aosp_gb;
odex_framework;
odex_system;
if [ "$1" = "-Data" ]; then
	odex_data;
fi
exit;
