#!/bin/bash
# Shortcuts
CMC_HOME=$(dirname $0)
MAIN=". ./CMCompiler"
CMC_CONFIG="$HOME/.cmcrc"
CMC_TOOLS="$CMC_HOME/tools/t"
CMC_SCRIPTS="$CMC_HOME/tools/s"
CMC_FUNCTIONS="$CMC_HOME/f"
CMC_DELETED="/tmp/CMC_DELETED_FILES"
TMPX="/tmp/CM_BUILD"
TMP_REPO="/tmp/found_repos"
CM_GIT="git://github.com/CyanogenMod/android.git"
DEFAULT_REPO_HOME="$HOME/Development/CM-GB"
GOG_REPO="https://dl-ssl.google.com/dl/googlesource/git-repo/repo"
#######################################################
#
# Start of the functions
#
#######################################################
function chk_tmp() {
if [ -f $TMPX ] || [ -f $TMP_REPO ] || [ -f $CMC_DELETED ]; then
	rm -f $TMPX
	rm -f $TMP_REPO
	rm -rf $CMC_DELETED
fi
}

function get_colors_set() {
# Colors
toff="\e[0m"  # Color off
tblk="\e[0;30m" # Black
tred="\e[0;31m" # Red
tgrn="\e[0;32m" # Green
tylw="\e[0;33m" # Yellow
tblu="\e[0;34m" # Blue
tprpl="\e[0;35m" # Purple
tcyn="\e[0;36m" # Cyan
# Light Colors
ltblk="\e[1;30m" # Black
ltred="\e[1;31m" # Red
ltgrn="\e[1;32m" # Green
ltylw="\e[1;33m" # Yellow
ltblu="\e[1;34m" # Blue
ltprpl="\e[1;35m" # Purple
ltcyn="\e[1;36m" # Cyan

CLR="$ltgrn"
CONF_COLOR_CHK=$(grep COLOR $CMC_CONFIG |wc -l)
CONF_COLOR_SET=$(grep COLOR $CMC_CONFIG |awk '{print $2}')
if [ "$CONF_COLOR_CHK" = "1" ]; then
	CLR="$CONF_COLOR_SET"
fi
}

function chk_cmc_config() {
if [ ! -f $CMC_CONFIG ]; then
	touch $CMC_CONFIG
fi

CONF_X="DEVICE_MAN"
CHK_MAN_CONF=$(grep $CONF_X $CMC_CONFIG | awk '{print $2}')
CHK_MAN_CONF_W=$(grep $CONF_X $CMC_CONFIG | awk '{print $2}' |wc -l)
if [ "$CHK_MAN_CONF_W" = "1" ]; then
	DEVICE_MAN=$CHK_MAN_CONF
else
	DEVICE_MAN="Unknown"
fi
CONF_X2="DEVICE_MOD"
CHK_MOD_CONF=$(grep $CONF_X2 $CMC_CONFIG | awk '{print $2}')
CHK_MOD_CONF_W=$(grep $CONF_X2 $CMC_CONFIG | awk '{print $2}' |wc -l)
if [ "$CHK_MOD_CONF_W" = "1" ]; then
	DEVICE_MOD=$CHK_MOD_CONF
else
	DEVICE_MOD="Unknown"
fi
}

function chk_repo_path() {
clear
chk_tmp
echo "Looking for currently installed repos..."
if [ ! -f $CMC_CONFIG ]; then
	touch $CMC_CONFIG
fi
CMC_CONFIG_REPO=$(grep REPO $CMC_CONFIG |awk '{print $2}')
CMC_CONFIG_REPO_CHK=$(grep REPO $CMC_CONFIG |wc -l)
CHK_4_REPO=$(find $CMC_CONFIG_REPO -type d -iname .repo |wc -l)
if [ "$CMC_CONFIG_REPO_CHK" != "1" ];then
	if [ "$CHK_4_REPO" = "0" ]; then
		echo "No found repos creating a folder now."
		echo "You might want to setup the repo before doing much!"
		echo "Setting up a default repo for you here: $DEFAULT_REPO_HOME"
		mkdir -p $DEFAULT_REPO_HOME
		sleep 2
		. ./menu_items/setup_cm_repo
	fi
	CHK_4_REPO=$(find $HOME -type d -iname .repo |cut -d"." -f"1")
	CHK_4_REPO_LST="$CHK_4_REPO"
	for repo in $CHK_4_REPO_LST; do
		CHK_REPO_SIZE=$(du -sh $repo)
		if [ "$CHK_REPO_SIZE" < "15" ]; then
			echo "SMALL: $repo" >> $TMP_REPO
		else
			echo "REPO: $repo" >> $TMP_REPO
			echo "REPO: $repo" >> $CMC_CONFIG
		fi
	done
elif [ "$CMC_CONFIG_REPO_CHK" = "1" ] && [ "$CHK_4_REPO" = "0" ];then
	clear
	echo "Found $CMC_CONFIG_REPO in $CMC_CONFIG, but no repo, you will need a repo to use this."
	echo "Are you sure you want to use this path? No will remove this entry!"
	echo -n "( Y/n) default: yes > "
	read response
	case $response in
		[nN] | [n|N][O|o] )
			sed ""$(grep -n0 REPO $CMC_CONFIG |cut -d":" -f"1")"d" $CMC_CONFIG > .tmp && mv .tmp $CMC_CONFIG
			chk_repo_path;;
		*)
			REPO_PATH=$CMC_CONFIG_REPO
			. ./menu_items/setup_cm_repo
	esac
else
	REPO_PATH=$CMC_CONFIG_REPO
fi
FOUND_NUM=$(grep REPO $CMC_CONFIG |awk '{print $2}' |wc -l)
}

function list_em() {
COUNT=1
ls_files=$(ls $MORE_PATH |sort)
for x in $ls_files; do
	echo_list=$(echo -e ""$CLR"${COUNT}"$toff") $x")
        echo "	"$echo_list"" >> $TMPX
        let COUNT=COUNT+1
done
chmod a+x $TMPX
}

function process_man_list() {
GET_LIST=$(sed -n "$option"p $TMPX |awk '{print $2}')
GET_LIST_W=$(sed -n "$option"p $TMPX |cut -d")" -f"1")
GET_LIST_CMC=$(grep DEVICE_MAN $CMC_CONFIG |wc -l)
GET_LIST_CMC_SED=$(grep DEVICE_MAN $CMC_CONFIG)
#GET_LIST_CMC_SED_MOD=$(grep -n0 DEVICE_MON $CMC_CONFIG |cut -d":" -f"1")
if [ "$GET_LIST_W" != "0" ]; then
	DEVICE_MAN=$(echo "$GET_LIST")
	clear
	echo -e "Your Manufacturer is "$CLR"$DEVICE_MAN"$toff""
	if [ "$GET_LIST_CMC" = "1" ]; then
		sed s/"$GET_LIST_CMC_SED"/"DEVICE_MAN: $DEVICE_MAN"/g $CMC_CONFIG > .tmp && mv .tmp $CMC_CONFIG
		sed ""$(grep -n0 DEVICE_MOD $CMC_CONFIG |cut -d":" -f"1")"d" $CMC_CONFIG > .tmp && mv .tmp $CMC_CONFIG
	else
		echo "DEVICE_MAN: $DEVICE_MAN" >> $CMC_CONFIG
	fi
	chk_tmp
	sleep 2
	$MAIN
else
	DEVICE_MAN="Unknown"
	clear
	echo -e "Your Manufacturer is "$CLR"$DEVICE_MAN"$toff", please try again"
	chk_tmp
	sleep 2
	. ./menu_items/ch_manufacturer
fi
chk_tmp
}

function process_mod_list() {
GET_LIST=$(sed -n "$option"p $TMPX |awk '{print $2}')
GET_LIST_W=$(sed -n "$option"p $TMPX |cut -d")" -f"1")
GET_LIST_CMC=$(grep DEVICE_MOD $CMC_CONFIG |wc -l)
GET_LIST_CMC_SED=$(grep DEVICE_MOD $CMC_CONFIG)
if [ "$GET_LIST_W" != "0" ]; then
	DEVICE_MOD=$(echo "$GET_LIST")
	clear
	echo -e "Your model is "$CLR"$DEVICE_MOD"$toff""
	if [ "$GET_LIST_CMC" = "1" ]; then
		sed s/"$GET_LIST_CMC_SED"/"DEVICE_MOD: $DEVICE_MOD"/g $CMC_CONFIG > .tmp && mv .tmp $CMC_CONFIG
	else
		echo "DEVICE_MOD: $DEVICE_MOD" >> $CMC_CONFIG
	fi
	chk_tmp
	sleep 2
	$MAIN
else
	DEVICE_MOD="Unknown"
	clear
	echo -e "Your model is "$CLR"$DEVICE_MOD"$toff", please try again"
	chk_tmp
	sleep 2
	. ./menu_items/ch_model
fi
}

function process_plugin_list() {
GET_LIST=$(sed -n "$option"p $TMPX |awk '{print $2}')
GET_LIST_W=$(sed -n "$option"p $TMPX |cut -d")" -f"1")
if [ "$GET_LIST_W" != "0" ]; then
	PLUGIN=$(echo "$GET_LIST")
	. ./plugins/$PLUGIN/main
	chk_tmp
else
	clear
	echo -e ""$CLR"Unable"$toff" to find that plugin, please try again"
	chk_tmp
	sleep 2
	. ./menu_items/run_plugins
fi
}

function apply_theme_process() {
CHK_THEME_CONF=$(grep COLOR $CMC_CONFIG)
CHK_THEME_CONF_W=$(grep COLOR $CMC_CONFIG |wc -l)
if [ "$CHK_THEME_CONF_W" = "1" ]; then
	X=$(echo "$CHK_THEME_CONF" |awk '{print $2}')
	echo -e "Your new theme is "$CLR"$COLOR_DESC"$toff""
	sed "s/COLOR: .*/COLOR: \\$CUST_COLOR/g" $CMC_CONFIG > .tmp && mv .tmp $CMC_CONFIG
else
	echo -e "Your new theme is "$CLR"$COLOR_DESC"$toff""
	echo "COLOR: $CUST_COLOR" >> $CMC_CONFIG
fi
sleep 1
$MAIN
}

function chk_adb_running() {
chk_adb=$(adb devices |grep device |grep -v attached |wc -l)
if [ "$chk_adb" != "1" ]; then
	ADB_MSG=""$tred"N/A"$toff""
else
	ADB_MSG=""$CLR"Running"$toff""
fi
}

function reposync() {
nohup $REPO sync >> /tmp/repo_sync.log &
echo "Syncing the CM repo. $BRANCH branch. Progress: 0"
sleep 3
while true; do
	CHK_SYNC_PID=$(ps aux |grep repo |grep sync |grep python |wc -l)
	if [ "$CHK_SYNC_PID" != "1" ]; then
		break
	fi
	sleep 5
	SYNC_PROCESS=$(cat /tmp/repo_sync.log |wc -l)
	PERCENT=$(($SYNC_PROCESS / 210))
	clear
	echo -n "Syncing the CM repo. $BRANCH branch. Progress: $PERCENT"
done
}

function setup_cm_repo() {
if [ ! -d $DEFAULT_REPO_HOME ]; then
	clear
	echo "Something is very wrong, send an email to mrlithid@gmail.com"
	echo "error code 4"
	echo "Please try again."
	exit 4
fi

clear
curl -# $GOG_REPO > $CMC_TOOLS/repo
if [ -f $CMC_TOOLS/repo ]; then
	REPO="$CMC_TOOLS/repo"
	chmod a+x $REPO
else
	clear
	echo "Couldn't link repo correctly. Check your internet and try again."
	rm -rf $CMC_TOOLS/repo >> /dev/null
	$MAIN
fi
cd $DEFAULT_REPO_HOME
clear
echo -e "Is this new repo going to be ICS or GB? (i/"$CLR"G"$toff")
Default is GB.
"$CLR"NOTE:"$toff"
This will include all cyanogenmod repos to the best of my ability at a future date."
echo -n "> "
read response
case $response in
	[g|G])
		BRANCH="gingerbread";;
	[i/I])
		BRANCH="ics";;
	*)
		BRANCH="gingerbread";;
esac
clear
echo "You are now going to go into the repo script and this interface will not exist, 
don't worry though. You will be back!"
echo -n "Press any key to continue..."
read input
case $input in
	*)
		echo "BRANCH: $BRANCH" >> $CMC_CONFIG
		clear
		$REPO init -u $CM_GIT -b $BRANCH
		clear
		echo "Now we are going to sync the repo. This will take some time. Go play some MW3."
		echo -n "Press any key to continue..."
		read input
		case $input in
			*)
				reposync;;
		esac;;
esac
$MAIN
}

function run_remove_function() {
MSG_LEVEL=$1
if [ "$MSG_LEVEL" = "yes" ]; then
	clear
	$SCRIPT
	echo "$MSG"
	sleep 1
elif [ "$MSG_LEVEL" = "no" ]; then
	clear
	echo "$MSG"
	sleep 1
else
	echo "Something went wrong with the script... Sorry"
	sleep 1
	exit 5
fi
$MAIN
}

function finish_the_repo(){
cd $REPO_PATH
make installclean

FILES=$(cat $CMC_DELETED)
for i in $FILES; do
	rm -rf $i
done

repo sync
chk_tmp

mv $(find $REPO/out -type f -iname update-cm-*-signed.zip) $HOME
mv $(find $REPO/out -type f -iname *.md5sum) $HOME
H_ROM=$(ls $HOME/update-cm-*-signed.zip)
clear
echo "Your files are located:"
echo "Rom: $H_ROM"
md5sum $HOME/*.md5sum
echo
echo -e "Press any key to continue..."
read response
case $response in
	*)$MAIN;;
esac
}

function compile_cm() {
WHICH_REPO=$(grep BRANCH $CMC_CONFIG |awk '{print $2}')

if [ "$WHICH_REPO" = "gingerbread" ]; then
	chk_adb_running
	cd $REPO_PATH/devices/$DEVICE_MAN/$DEVICE_MOD
	if [ -f extract-files.sh ]; then
		./extract-files.sh
	fi

	cd $REPO_PATH
	$REPO_PATH/vendor/cyanogen/get-rommanager

	. build/envsetup.sh

	make installclean
	brunch $DEVICE_MOD

	finish_the_repo

elif [ "$WHICH_REPO" = "ics" ]; then
	chk_adb_running
	cd $REPO_PATH/devices/$DEVICE_MAN/$DEVICE_MOD
	if [ -f extract-files.sh ]; then
		./extract-files.sh
	fi

	cd $REPO_PATH/vendor/cm
	./get-prebuilts

	cd $REPO_PATH

	. build/envsetup.sh

	make installclean
	brunch $DEVICE_MOD

	finish_the_repo

else
	clear
	echo "There appears to be an issue with your configuration."
	echo "Please look at $CMC_CONFIG."
	sleep 2
	$MAIN
fi
}
#######################################################
#
# End of the functions
#
#######################################################
