#!/bin/bash
# By: noqqe (https://github.com/noqqe/bash-progress-bar)
SLEEP="sleep 2"

function cyanogenmod(){
COLUMNS=$(tput cols)
ROWS=$(tput lines)
TOP=$(($ROWS / 2 - 8))

w=$(( $COLUMNS / 2 - 37))
clear
for i in $(seq 1 "$TOP"); do echo; done
echo " _______                                                          _ " | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
echo "(_______)$FUNCTIONX| |" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
echo " _      _   _ _____ ____   ___   ____ _____ ____  ____   ___   __| |" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
echo "| |    | | | (____ |  _ \ / _ \ / _  | ___ |  _ \|    \ / _ \ / _  |" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
echo "| |____| |_| / ___ | | | | |_| ( (_| | ____| | | | | | | |_| ( (_| |" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
echo " \______)__  \_____|_| |_|\___/ \___ |_____)_| |_|_|_|_|\___/ \____|" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
echo "       (____/                  (_____|" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
echo
}

while true; do
cyanogenmod
w=$(( $COLUMNS / 2 - 28))
echo "[======                                              ]" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
for i in $(seq 1 "$TOP"); do echo; done
$SLEEP
cyanogenmod
w=$(( $COLUMNS / 2 - 28))
echo "[      =======                                       ]" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
for i in $(seq 1 "$TOP"); do echo; done
$SLEEP
cyanogenmod
w=$(( $COLUMNS / 2 - 28))
echo "[            =======                                 ]" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
for i in $(seq 1 "$TOP"); do echo; done
$SLEEP
cyanogenmod
w=$(( $COLUMNS / 2 - 28))
echo "[                  =======                           ]" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
for i in $(seq 1 "$TOP"); do echo; done
$SLEEP
cyanogenmod
w=$(( $COLUMNS / 2 - 28))
echo "[                        =======                     ]" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
for i in $(seq 1 "$TOP"); do echo; done
$SLEEP
cyanogenmod
w=$(( $COLUMNS / 2 - 28))
echo "[                              =======               ]" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
for i in $(seq 1 "$TOP"); do echo; done
$SLEEP
cyanogenmod
w=$(( $COLUMNS / 2 - 28))
echo "[                                    =======         ]" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
for i in $(seq 1 "$TOP"); do echo; done
$SLEEP
cyanogenmod
w=$(( $COLUMNS / 2 - 28))
echo "[                                          =======   ]" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
for i in $(seq 1 "$TOP"); do echo; done
$SLEEP
cyanogenmod
w=$(( $COLUMNS / 2 - 28))
echo "[                                                ====]" | while IFS= read -r line; do printf "%${w}s %s\n" '' "$line"; done
for i in $(seq 1 "$TOP"); do echo; done
$SLEEP
done
