#!/bin/sh

echo "$REPO_PATH/build/target/product/languages_full.mk" >> $CMC_DELETED
echo "$REPO_PATH/build/target/product/full_base.mk" >> $CMC_DELETED
echo "$REPO_PATH/build/target/product/locales_full.mk" >> $CMC_DELETED
if [ "$BRANCH" = "ics" ]; then
	echo "$REPO_PATH/build/target/product/languages_small.mk" >> $CMC_DELETED
fi

rm -rf $REPO_PATH/build/target/product/full_base.mk
rm -rf $REPO_PATH/build/target/product/languages_full.mk
rm -rf $REPO_PATH/external/svox/pico/lang/all_pico_languages.mk
rm -rf $REPO_PATH/build/target/product/locales_full.mk
if [ "$BRANCH" = "ics" ]; then
	rm -rf $REPO_PATH/build/target/product/languages_small.mk
fi

touch $REPO_PATH/build/target/product/full_base.mk
touch $REPO_PATH/build/target/product/languages_full.mk
touch $REPO_PATH/build/target/product/locales_full.mk
touch $REPO_PATH/external/svox/pico/lang/all_pico_languages.mk
if [ "$BRANCH" = "ics" ]; then
	touch $REPO_PATH/build/target/product/languages_small.mk
fi

if [ "$BRANCH" = "ics" ]; then
(cat << EOF) > $REPO_PATH/build/target/product/full_base.mk
#
# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This is a build configuration for a full-featured build of the
# Open-Source part of the tree. It's geared toward a US-centric
# build of the emulator, but all those aspects can be overridden
# in inherited configurations.

PRODUCT_PACKAGES := \\
    drmserver \\
    libdrmframework \\
    libdrmframework_jni \\
    libfwdlockengine \\
    VideoEditor \\
    WAPPushManager

# Additional settings used in all AOSP builds
PRODUCT_PROPERTY_OVERRIDES := \\
    ro.com.android.dateformat=MM-dd-yyyy \\
    ro.config.ringtone=Ring_Synth_04.ogg \\
    ro.config.notification_sound=pixiedust.ogg

# Put en_US first in the list, so make it default.
PRODUCT_LOCALES := en_US

# Get some sounds
\$(call inherit-product-if-exists, frameworks/base/data/sounds/AllAudio.mk)

# Get the TTS language packs
\$(call inherit-product-if-exists, external/svox/pico/lang/all_pico_languages.mk)

# Get everything else from the parent package
\$(call inherit-product, \$(SRC_TARGET_DIR)/product/generic_no_telephony.mk)
EOF

else

(cat << EOF) > $REPO_PATH/build/target/product/full_base.mk
#
# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This is a build configuration for a full-featured build of the
# Open-Source part of the tree. This is a base configuration to
# bes used for AOSP builds on various target devices.

PRODUCT_PACKAGES := \\
    VoiceDialer

# Additional settings used in all AOSP builds
PRODUCT_PROPERTY_OVERRIDES := \\
    keyguard.no_require_sim=true

# Put en_US first in the list, to make it default.
PRODUCT_LOCALES := en_US

# Pick up some sounds - stick with the short list to save space
# on smaller devices.
\$(call inherit-product-if-exists, frameworks/base/data/sounds/OriginalAudio.mk)

# Get the TTS language packs
\$(call inherit-product-if-exists, external/svox/pico/lang/all_pico_languages.mk)

\$(call inherit-product, \$(SRC_TARGET_DIR)/product/generic.mk)
EOF

fi
(cat << EOF) > $REPO_PATH/external/svox/pico/lang/all_pico_languages.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file simply inherits from all the know language packs.

\$(call inherit-product, external/svox/pico/lang/PicoLangEnUsInSystem.mk)
EOF
(cat << EOF) > $REPO_PATH/build/target/product/locales_full.mk
# The locales from the ICU "-large.dat" data set.
# See external/icu4c/stubdata.
# This is distinct from "languages_full.mk", which contains those locales for
# which we have translations. If you like, this file is i18n rather than l18n.
PRODUCT_LOCALES := en_US
EOF
(cat << EOF) > $REPO_PATH/build/target/product/languages_full.mk
# The locales from the ICU "-large.dat" data set.
# See external/icu4c/stubdata.
# This is distinct from "languages_full.mk", which contains those locales for
# which we have translations. If you like, this file is i18n rather than l18n.
PRODUCT_LOCALES := en_US
EOF
if [ "$BRANCH" = "ics" ]; then
(cat << EOF) > $REPO_PATH/build/target/product/languages_small.mk
# The locales from the ICU "-large.dat" data set.
# See external/icu4c/stubdata.
# This is distinct from "languages_full.mk", which contains those locales for
# which we have translations. If you like, this file is i18n rather than l18n.
PRODUCT_LOCALES := en_US
EOF
fi
exit 0
