#!/bin/sh
# Written by lithid (mrlithid@gmail.com)
echo "$REPO_PATH/vendor/cyanogen/products/common_full.mk" >> $CMC_DELETED

rm -rf $REPO_PATH/vendor/cyanogen/products/common_full.mk
touch $REPO_PATH/vendor/cyanogen/products/common_full.mk

(cat << EOF) > $REPO_PATH/vendor/cyanogen/products/common_full.mk

# Inherit common CM stuff
\$(call inherit-product, vendor/cyanogen/products/common.mk)

# Bring in all audio files
include frameworks/base/data/sounds/AllAudio.mk

# Theme packages
include vendor/cyanogen/products/themes.mk

# Include extra dictionaries for LatinIME
PRODUCT_PACKAGE_OVERLAYS += vendor/cyanogen/overlay/dictionaries

# Default ringtone
PRODUCT_PROPERTY_OVERRIDES += \\
    ro.config.ringtone=Playa.ogg \\
    ro.config.notification_sound=regulus.ogg \\
    ro.config.alarm_alert=Alarm_Beep_03.ogg
EOF
