#!/bin/bash
# Written by lithid (mrlithid@gmail.com)

. $CMC_HOME/tools/f/compile_functions
COUNT="0"

if [ "$1" = "--check" ]; then
	PKG_LIST=(git-core gnupg flex bison gperf libsdl1.2-dev libesd0-dev libwxgtk2.6-dev squashfs-tools build-essential zip curl libncurses5-dev zlib1g-dev sun-java6-jdk pngcrush schedtool)
	COUNT="1"
	for x in ${PKG_LIST[@]}; do
		CHK=$(dpkg –get-selections | grep -v deinstall |grep -c $x)
		if [ "$CHK" -eq "1" ]; then
			let COUNT=COUNT+1
		fi
	done
	COUNT_1="${COUNT}"
	if [ "$BITS" = "x86_64" ]; then
		PKG_LIST=(g++-multilib lib32z1-dev lib32ncurses5-dev lib32readline5-dev gcc-4.3-multilib g++-4.3-multilib)
		COUNT="1"
		for x in ${PKG_LIST[@]}; do
			CHK=$(dpkg –get-selections | grep -v deinstall |grep -c $x)
			if [ "$CHK" -eq "1" ]; then
				let COUNT=COUNT+1
			fi
		done
	fi
	if  [ "$COUNT" -gt "0" ]; then
		export PKG_COUNT="Missing: ${tred}${COUNT}{toff} Packages"
	else
		export PKG_COUNT="${CLR}Packages good{toff}"
	fi
elif [ "$1" = "--install" ]; then
	clear
	echo "This option doesn't work yet"
	read -sn 1 -p "Press any key to go back to setup menu..."
else
fi
